# Generated by Django 5.0.3 on 2024-03-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price_nightly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('percentage_offer', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('spots_available', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('AG', 'Agent'), ('CL', 'Client')], default='CL', max_length=2)),
            ],
        ),
    ]
