# Generated by Django 5.0.3 on 2024-03-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='path_img',
            field=models.FilePathField(default=''),
        ),
    ]
