# Generated by Django 5.0.3 on 2024-03-31 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_made',
            field=models.DateField(default=datetime.datetime(2024, 3, 31, 8, 51, 39, 583405, tzinfo=datetime.timezone.utc)),
        ),
    ]
