# Generated by Django 5.0.3 on 2024-03-31 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_reservation_destination_reservation_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_made',
            field=models.DateField(default=datetime.datetime(2024, 3, 31, 11, 24, 27, 275886, tzinfo=datetime.timezone.utc)),
        ),
    ]
